version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
#Don't build twice for PR's to same repo
skip_branch_with_pr: true
environment:
    AUTOUPDATER_Duplicati_SKIP_UPDATE: 1
    COVERALLS_REPO_TOKEN:
        secure: szQsrkP5rvra8L60SomD73/dFvRwot0UuyA566zqzI2qmLOr+MhLN0AyC8BTbhYY
before_build:
    - ps: $env:UNITTEST_BASEFOLDER = "$Env:APPVEYOR_BUILD_FOLDER" + "\testdata"
build:
    project: Duplicati.sln
    verbosity: minimal
test_script:
    - ps: |
        Start-FileDownload https://s3.amazonaws.com/duplicati-test-file-hosting/DSMCBE.zip

        7z x DSMCBE.zip -otestdata
        mkdir .\testData\data
        
        dotnet test --verbosity normal Duplicati.sln
        $testsPassed = $?

        # Upload test results to AppVeyor.
        $wc = New-Object "System.Net.WebClient"
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "TestResults.xml")

        if (!$testsPassed) {
            throw "Tests failed."
        }
