language: csharp
mono: none
dotnet: 5.0.101
services: docker
before_install:
  - sudo apt-get install moreutils
  - set -o pipefail
env:
  global:
    - USAGEREPORTER_Duplicati_LEVEL=none
    - AUTOUPDATER_Duplicati_SKIP_UPDATE=1
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/../.build
    - TEST_DIR=${TRAVIS_BUILD_DIR}/../.test
    - ROOT_DIR="$TRAVIS_BUILD_DIR"

# matrix expansion within jobs would be good:
# https://github.com/travis-ci/travis-ci/issues/8295

# There is one cache per branch, so concurrent builds on different branches possible!
# DO NOT SET ENVIRONMENT VARIABLES WITHIN JOBS, OR CACHES WILL NOT BE SHARED AMONGST JOBS!


jobs:
  include:
    - stage: build
      cache:
        directories:
          - $BUILD_DIR
      script:
        - dotnet publish -r linux-x64 -o $BUILD_DIR ${ROOT_DIR}/Duplicati.sln
        - cp -R ${ROOT_DIR}/guiTests $BUILD_DIR/


    - stage: tests
      script:
        - dotnet test --verbosity normal ${ROOT_DIR}/Duplicati.sln

    - stage: tests
      cache:
        directories:
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/selenium_job.sh
      addons:
        sauce_connect:
          username: $SAUCE_USERNAME
          access_key: $SAUCE_ACCESS_KEY
