name: Freebsd Artifacts

on:
  push:
    branches: [ feature/net5-freebsd ]
  pull_request:
    branches: [ feature/net5-freebsd ]

jobs:
  zip:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Download dotnet
      # http://bit.ly/3hceESr = dotnet-sdk-5.0.203-freebsd-x64.tar.gz
      # See also https://github.com/sec/dotnet-core-freebsd-source-build
      # See also https://github.com/Thefrank/dotnet-freebsd-crossbuild
      run: curl -L http://bit.ly/3hceESr -o dn.tgz
    - name: Build native FreeBSD lib
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        sync: sshfs
        prepare: pkg install -y curl libinotify libunwind git cmake ninja bash wget icu
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          BUILD_DIR=`pwd`
          cd /var/tmp
          mkdir dn
          cd dn
          tar -xzf ${BUILD_DIR}/dn.tgz
          cd ${BUILD_DIR}
          /var/tmp/dn/dotnet restore --runtime=freebsd-x64 Duplicati.sln
          /var/tmp/dn/dotnet publish -c Release --runtime=freebsd-x64 -o publish Duplicati.sln
    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: duplicati-freebsd-x64
        path: publish
  tests:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Download dotnet
      # http://bit.ly/3hceESr = dotnet-sdk-5.0.203-freebsd-x64.tar.gz
      # See also https://github.com/sec/dotnet-core-freebsd-source-build
      # See also https://github.com/Thefrank/dotnet-freebsd-crossbuild
      run: curl -L http://bit.ly/3hceESr -o dn.tgz
    - name: Build native FreeBSD lib
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        sync: sshfs
        prepare: pkg install -y curl libinotify libunwind git cmake ninja bash wget icu
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          BUILD_DIR=`pwd`
          cd /var/tmp
          mkdir dn
          cd dn
          tar -xzf ${BUILD_DIR}/dn.tgz
          cd ${BUILD_DIR}
          /var/tmp/dn/dotnet restore --runtime=freebsd-x64 Duplicati.sln
          /var/tmp/dn/dotnet build --no-restore --runtime=freebsd-x64 Duplicati.sln
          /var/tmp/dn/dotnet test --no-build --verbosity normal --runtime=freebsd-x64 Duplicati.sln
