name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - name: Install mono
      run: sudo apt-get install mono-complete

    - name: Checkout $GITHUB_SHA from $GITHUB_REF
      uses: actions/checkout@v2

    - name: Build AutoUpdateBuilder
      run: |
        nuget restore BuildTools/AutoUpdateBuilder/AutoUpdateBuilder.sln
        msbuild -p:Configuration=Release BuildTools/AutoUpdateBuilder/AutoUpdateBuilder.sln

    # - name: Build DependencyFinder
    #   run: |
    #     nuget restore BuildTools/DependencyFinder/DependencyFinder.sln
    #     msbuild -p:Configuration=Release BuildTools/DependencyFinder/DependencyFinder.sln

    - name: Build GnupgSigningTool
      run: |
        nuget restore BuildTools/GnupgSigningTool/GnupgSigningTool.sln
        msbuild -p:Configuration=Release BuildTools/GnupgSigningTool/GnupgSigningTool.sln

    - name: Build UpdateVersionStamp
      run: |
        nuget restore BuildTools/UpdateVersionStamp/UpdateVersionStamp.sln
        msbuild -p:Configuration=Release BuildTools/UpdateVersionStamp/UpdateVersionStamp.sln

    - name: Build Duplicati
      run: |
        nuget restore Duplicati.sln
        msbuild -p:Configuration=Release -p:DefineConstants=ENABLE_GTK Duplicati.sln

    - name: Run Unit Tests
      run: |
        nuget install NUnit.Runners -Version 3.12.0 -OutputDirectory nunit
        mono nunit/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll --where:cat==Utility --work=TestResults

    - name: Publish Unit Test Results
      uses: MirrorNG/nunit-reporter@v1.0.9
      if: always()
      with:
        path: TestResults/**/*.xml
        access-token: ${{ secrets.GITHUB_TOKEN }}
