on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - name: Install mono
      run: sudo apt-get install mono-complete

    - name: Checkout $GITHUB_SHA from $GITHUB_REF
      uses: actions/checkout@v2
